name: movie_app
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  dio: ^5.1.1
  bloc: ^8.1.1
  flutter_bloc: ^8.1.2
  flutter_config: ^2.0.2
  carousel_slider: ^4.2.1
  image: ^3.0.2
  cached_network_image: ^3.2.1
  flutter_svg: ^2.0.5
  pull_to_refresh: ^2.0.0
  flutter_launcher_icons: ^0.11.0
  image_picker: ^0.8.7+4
  intl: ^0.18.1
  flutter_staggered_grid_view: ^0.6.2
  flutter_screenutil: ^5.9.0
  youtube_player_flutter: ^8.1.2
  shimmer: ^3.0.0
  lottie: ^2.6.0
  flutter_rating_bar: ^4.0.1

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - lib/shared_ui/assets/icons/home_icon.svg
    - lib/shared_ui/assets/icons/favorite_icon.svg
    - lib/shared_ui/assets/icons/search_icon.svg
    - lib/shared_ui/assets/icons/profile_icon.svg
    - lib/shared_ui/assets/icons/trending_icon.svg
    - lib/shared_ui/assets/icons/tv_show_icon.svg
    - lib/shared_ui/assets/icons/best_drama_icon.svg
    - lib/shared_ui/assets/icons/upcoming_icon.png
    - lib/shared_ui/assets/icons/top_rated_icon.svg
    - lib/shared_ui/assets/icons/popular_icon.svg
    - lib/shared_ui/assets/icons/now_playing_icon.svg
    - lib/shared_ui/assets/icons/trailer_icon.svg
    - lib/shared_ui/assets/icons/filter_icon.svg
    - lib/shared_ui/assets/icons/eye_open_icon.png
    - lib/shared_ui/assets/icons/eye_close_icon.png
    - lib/shared_ui/assets/images/primary_long_logo.png
    - lib/shared_ui/assets/images/primary_short_logo.png
    - lib/shared_ui/assets/images/background.png
    - lib/shared_ui/assets/images/no_image.png
    - lib/shared_ui/assets/animations/loading_animation.json
