import 'package:flutter/material.dart';

Color get noColor => const Color(0xFFFFFFFF).withOpacity(0);
Color get darkWhiteColor => const Color(0xFFF5F5F5);
Color get whiteColor => const Color(0xFFFFFFFF);
Color get whiteSmokeColor => const Color(0xFFf7f7f7);
Color get blackColor => const Color(0xFF000000);
Color get indigoColor => const Color(0xFF0d253f);
Color get lightGreenColor => const Color(0xFF90cea1);
Color get lightBlueColor => const Color(0xFF01b4e4);
Color get darkBlueColor => const Color(0xFF0d253f);
Color get greyColor => const Color(0xFF9C9C9C);
Color get lightGreyColor => const Color(0xFFC4C4C4);
Color get tealColor => const Color(0xFF4C9B94);
Color get darkTealColor => const Color(0xFF000C34);
Color get brownColor => const Color(0xff964B00);
Color get yellowColor => const Color(0xffefc01b);
Color get gainsBoroColor => const Color(0xFFE6E6E6);
Color get cyanColor => const Color(0xFF00FFFF);
Color get pinkColor => const Color(0xFFF50057);
Color get venetianRedColor => const Color(0xFFc60000);
Color get redColor => const Color(0xFFFF0000);
Color get skyBlueColor => const Color(0xFF87CEEB);
Color get brightNavyBlue => const Color(0xFF0468BA);
